/**
 * Core newsroom org seed — leadership + desks + writing/digital.
 * City local editors / 81 SMM are linked or bulk-seeded separately.
 */
import type {
  AgentDepartmentId,
  AgentRoleTemplateId,
  AutonomyLevel,
  NewsroomAgent,
} from '@/types/newsroomOs'
import type { CmsPermission } from '@/types/cms'
import {
  CITY_SMM_ROLE_INSTRUCTIONS,
  SOCIAL_DIRECTOR_INSTRUCTIONS,
} from '@/services/newsroomOs/smmPlaybook'

export interface OrgSeedSpec {
  id: string
  name: string
  displayName: string
  description: string
  roleTemplateId: AgentRoleTemplateId
  departmentId: AgentDepartmentId
  managerAgentId: string | null
  autonomyLevel: AutonomyLevel
  categories: string[]
  territories: string[]
  permissions: CmsPermission[]
  tools: string[]
}

const BASE_PERMS: CmsPermission[] = ['ai:use', 'news:read']

export const ORG_SEED_SPECS: OrgSeedSpec[] = [
  {
    id: 'agent-eic',
    name: 'genel-yayin-yonetmeni',
    displayName: 'Genel Yayın Yönetmeni AI',
    description: 'Tüm AI newsroom operasyonunun en üst yöneticisi',
    roleTemplateId: 'editor-in-chief',
    departmentId: 'executive',
    managerAgentId: null,
    autonomyLevel: 2,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'agents:manage', 'news:publish', 'ai:configure'],
    tools: ['delegate', 'approve', 'escalate'],
  },
  {
    id: 'agent-deputy',
    name: 'genel-yayin-yardimcisi',
    displayName: 'Genel Yayın Yönetmen Yardımcısı AI',
    description: 'EIC yardımcısı — koordinasyon ve escalation',
    roleTemplateId: 'deputy-editor',
    departmentId: 'executive',
    managerAgentId: 'agent-eic',
    autonomyLevel: 2,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'agents:delegate', 'news:publish'],
    tools: ['delegate', 'approve'],
  },
  {
    id: 'agent-news-director',
    name: 'haber-muduru',
    displayName: 'Haber Müdürü AI',
    description: 'Masalar ve yazı işleri koordinasyonu',
    roleTemplateId: 'news-director',
    departmentId: 'newsroom',
    managerAgentId: 'agent-eic',
    autonomyLevel: 2,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'news:edit', 'news:publish', 'agents:delegate'],
    tools: ['assign-desk', 'priority'],
  },
  {
    id: 'agent-desk-gundem',
    name: 'gundem-muduru',
    displayName: 'Gündem Müdürü AI',
    description: 'Ulusal gündem masası',
    roleTemplateId: 'desk-editor',
    departmentId: 'desk-gundem',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 2,
    categories: ['gundem', 'siyaset', 'son-dakika'],
    territories: [],
    permissions: [...BASE_PERMS, 'news:edit', 'news:create'],
    tools: ['write', 'research'],
  },
  {
    id: 'agent-desk-economy',
    name: 'ekonomi-muduru',
    displayName: 'Ekonomi Müdürü AI',
    description: 'Ekonomi / finans masası',
    roleTemplateId: 'desk-editor',
    departmentId: 'desk-economy',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 2,
    categories: ['ekonomi', 'finans', 'borsa'],
    territories: [],
    permissions: [...BASE_PERMS, 'news:edit', 'news:create'],
    tools: ['write', 'research'],
  },
  {
    id: 'agent-desk-sports',
    name: 'spor-muduru',
    displayName: 'Spor Müdürü AI',
    description: 'Spor masası',
    roleTemplateId: 'desk-editor',
    departmentId: 'desk-sports',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 2,
    categories: ['spor', 'futbol', 'basketbol'],
    territories: [],
    permissions: [...BASE_PERMS, 'news:edit', 'news:create'],
    tools: ['write', 'research'],
  },
  {
    id: 'agent-desk-local',
    name: 'yerel-yayin-muduru',
    displayName: 'Yerel Yayın Müdürü AI',
    description: '81 il yerel editör ağı yöneticisi',
    roleTemplateId: 'desk-editor',
    departmentId: 'desk-local',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 2,
    categories: ['yerel-haber', 'yerel-duyuru'],
    territories: [],
    permissions: [...BASE_PERMS, 'news:edit', 'locations:manage', 'agents:delegate'],
    tools: ['assign-city', 'write'],
  },
  {
    id: 'agent-desk-world',
    name: 'dunya-muduru',
    displayName: 'Dünya Müdürü AI',
    description: 'Uluslararası haber masası',
    roleTemplateId: 'desk-editor',
    departmentId: 'desk-world',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 2,
    categories: ['dunya'],
    territories: [],
    permissions: [...BASE_PERMS, 'news:edit', 'news:create'],
    tools: ['write', 'research'],
  },
  {
    id: 'agent-desk-politics',
    name: 'politika-muduru',
    displayName: 'Politika Müdürü AI',
    description: 'Siyaset / politika masası',
    roleTemplateId: 'desk-editor',
    departmentId: 'desk-politics',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 1,
    categories: ['siyaset'],
    territories: [],
    permissions: [...BASE_PERMS, 'news:edit', 'news:create'],
    tools: ['write', 'research', 'escalate'],
  },
  {
    id: 'agent-desk-tech',
    name: 'teknoloji-muduru',
    displayName: 'Teknoloji Müdürü AI',
    description: 'Teknoloji / bilim masası',
    roleTemplateId: 'desk-editor',
    departmentId: 'desk-tech',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 2,
    categories: ['teknoloji', 'bilim'],
    territories: [],
    permissions: [...BASE_PERMS, 'news:edit', 'news:create'],
    tools: ['write', 'research'],
  },
  {
    id: 'agent-desk-health',
    name: 'saglik-muduru',
    displayName: 'Sağlık Müdürü AI',
    description: 'Sağlık masası — dikkatli iddia dili',
    roleTemplateId: 'desk-editor',
    departmentId: 'desk-health',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 1,
    categories: ['saglik'],
    territories: [],
    permissions: [...BASE_PERMS, 'news:edit', 'news:create'],
    tools: ['write', 'research', 'escalate'],
  },
  {
    id: 'agent-desk-culture',
    name: 'kultur-muduru',
    displayName: 'Kültür Sanat Müdürü AI',
    description: 'Kültür / sanat masası',
    roleTemplateId: 'desk-editor',
    departmentId: 'desk-culture',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 2,
    categories: ['kultur', 'sinema', 'tiyatro', 'konser'],
    territories: [],
    permissions: [...BASE_PERMS, 'news:edit', 'news:create'],
    tools: ['write', 'research'],
  },
  {
    id: 'agent-desk-lifestyle',
    name: 'yasam-muduru',
    displayName: 'Yaşam / Magazin Müdürü AI',
    description: 'Yaşam ve magazin masası',
    roleTemplateId: 'desk-editor',
    departmentId: 'desk-lifestyle',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 2,
    categories: ['yasam', 'magazin'],
    territories: [],
    permissions: [...BASE_PERMS, 'news:edit', 'news:create'],
    tools: ['write', 'research'],
  },
  {
    id: 'agent-reporter',
    name: 'muhabir',
    displayName: 'Muhabir AI',
    description: 'Araştırma ve ham haber toplama',
    roleTemplateId: 'reporter',
    departmentId: 'newsroom',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 1,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'news:create'],
    tools: ['research', 'ingest'],
  },
  {
    id: 'agent-writer',
    name: 'haber-yazari',
    displayName: 'Haber Yazarı AI',
    description: 'Kaynak metinden editoryal yazım',
    roleTemplateId: 'writer',
    departmentId: 'writing',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 2,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'news:create', 'news:edit'],
    tools: ['write'],
  },
  {
    id: 'agent-fact-check',
    name: 'fact-check',
    displayName: 'Fact Check AI',
    description: 'İddia çıkarımı ve doğrulama',
    roleTemplateId: 'fact-checker',
    departmentId: 'writing',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 1,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS],
    tools: ['fact-check', 'evidence'],
  },
  {
    id: 'agent-quality',
    name: 'quality-control',
    displayName: 'Quality Controller AI',
    description: 'Editoryal kalite kontrol',
    roleTemplateId: 'quality-controller',
    departmentId: 'writing',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 1,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS],
    tools: ['quality-score'],
  },
  {
    id: 'agent-legal',
    name: 'legal-risk',
    displayName: 'Legal / Risk AI',
    description: 'Hakaret, KVKK, masumiyet, telif risk taraması',
    roleTemplateId: 'legal-risk',
    departmentId: 'writing',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 1,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS],
    tools: ['risk-scan'],
  },
  {
    id: 'agent-seo',
    name: 'seo-editor',
    displayName: 'SEO Editor AI',
    description: 'Başlık, meta, discover uyumu',
    roleTemplateId: 'seo-editor',
    departmentId: 'writing',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 2,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'seo:edit'],
    tools: ['seo-optimize'],
  },
  {
    id: 'agent-visual',
    name: 'visual-editor',
    displayName: 'Visual Editor AI',
    description: 'Görsel seçim ve alt metin',
    roleTemplateId: 'visual-editor',
    departmentId: 'writing',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 2,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS],
    tools: ['image-select'],
  },
  {
    id: 'agent-digital-director',
    name: 'dijital-yayin-muduru',
    displayName: 'Dijital Yayın Müdürü AI',
    description: 'Discover, push, video, sosyal üst yönetim',
    roleTemplateId: 'publisher',
    departmentId: 'digital',
    managerAgentId: 'agent-eic',
    autonomyLevel: 2,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'social:manage', 'agents:delegate'],
    tools: ['distribute', 'push'],
  },
  {
    id: 'agent-discover',
    name: 'discover-agent',
    displayName: 'Discover Agent AI',
    description: 'Discover / keşfet yüzeyleri için içerik seçimi',
    roleTemplateId: 'publisher',
    departmentId: 'digital',
    managerAgentId: 'agent-digital-director',
    autonomyLevel: 2,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS],
    tools: ['discover-curate'],
  },
  {
    id: 'agent-push',
    name: 'push-agent',
    displayName: 'Push Agent AI',
    description: 'Push bildirim önerileri — human approval eşikleri',
    roleTemplateId: 'publisher',
    departmentId: 'digital',
    managerAgentId: 'agent-digital-director',
    autonomyLevel: 1,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS],
    tools: ['push-propose'],
  },
  {
    id: 'agent-video',
    name: 'video-agent',
    displayName: 'Video Agent AI',
    description: 'Video / reels metin ve format önerileri',
    roleTemplateId: 'visual-editor',
    departmentId: 'digital',
    managerAgentId: 'agent-digital-director',
    autonomyLevel: 2,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'video:read'],
    tools: ['video-script'],
  },
  {
    id: 'agent-social-director',
    name: 'social-media-director',
    displayName: 'Social Media Director AI',
    description: '81 İl SMM ağının yöneticisi',
    roleTemplateId: 'social-director',
    departmentId: 'social',
    managerAgentId: 'agent-digital-director',
    autonomyLevel: 2,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'social:manage', 'social:publish', 'agents:delegate'],
    tools: ['smm-assign', 'campaign', 'escalate'],
  },
  {
    id: 'agent-algorithm',
    name: 'algorithm-analyst',
    displayName: 'Algorithm Agent',
    description: 'Feed ağırlık önerileri — production değişikliği yapmaz',
    roleTemplateId: 'algorithm-analyst',
    departmentId: 'algorithm',
    managerAgentId: 'agent-digital-director',
    autonomyLevel: 0,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'algorithm:view'],
    tools: ['analyze-feed', 'propose-weights'],
  },
  {
    id: 'agent-learning',
    name: 'learning-analyst',
    displayName: 'Learning Agent',
    description: 'Diff analizi → rule proposal (human approve zorunlu)',
    roleTemplateId: 'learning-analyst',
    departmentId: 'learning',
    managerAgentId: 'agent-eic',
    autonomyLevel: 0,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'ai:configure'],
    tools: ['diff-analyze', 'propose-rule'],
  },
]

export const ROLE_TEMPLATE_LABELS: Record<AgentRoleTemplateId, string> = {
  'editor-in-chief': 'Genel Yayın Yönetmeni',
  'deputy-editor': 'Yardımcı',
  'news-director': 'Haber Müdürü',
  'desk-editor': 'Masa Editörü',
  'local-editor': 'Yerel Editör',
  reporter: 'Muhabir',
  writer: 'Yazar',
  'fact-checker': 'Fact Checker',
  'quality-controller': 'Quality',
  'legal-risk': 'Legal/Risk',
  'seo-editor': 'SEO',
  'visual-editor': 'Visual',
  'social-director': 'Social Director',
  'city-smm': 'İl SMM',
  'algorithm-analyst': 'Algorithm',
  'learning-analyst': 'Learning',
  publisher: 'Yayın',
}

export const DEPARTMENT_LABELS: Record<AgentDepartmentId, string> = {
  executive: 'Üst Yönetim',
  newsroom: 'Haber Merkezi',
  'desk-gundem': 'Gündem Masası',
  'desk-local': 'Yerel Masa',
  'desk-sports': 'Spor Masası',
  'desk-economy': 'Ekonomi Masası',
  'desk-world': 'Dünya Masası',
  'desk-politics': 'Politika Masası',
  'desk-tech': 'Teknoloji Masası',
  'desk-health': 'Sağlık Masası',
  'desk-culture': 'Kültür Sanat Masası',
  'desk-lifestyle': 'Yaşam / Magazin Masası',
  writing: 'Yazı İşleri',
  digital: 'Dijital Yayın',
  social: 'Sosyal Medya',
  algorithm: 'Algoritma',
  learning: 'Öğrenme',
}

/** Default agent-level custom instructions applied on first seed only. */
export const ROLE_DEFAULT_INSTRUCTIONS: Partial<Record<AgentRoleTemplateId, string>> = {
  'editor-in-chief':
    'Tüm haber odası kalitesinden sorumlusun. Yayın kararlarında hızdan önce güvenilirlik. Escalation ve human approval eşiklerini koru.',
  'news-director':
    'Masalar arası önceliklendirme yap. Çift haberi engelle, masa atamasını netleştir, fact-check ve legal riski atlama.',
  'desk-editor':
    'Sadece kendi masa kategorilerinde yaz/düzenle. Kaynağı belirt, spekülasyon ekleme, sansasyon dilinden kaçın.',
  'local-editor':
    'Yalnızca kendi il/ilçe bağlamında yaz. Yerel isimleri doğrula, ulusal haberi yerel gibi sunma.',
  'fact-checker':
    'Doğrulanabilir iddiaları çıkar. VERIFIED / PARTIALLY_VERIFIED / UNVERIFIED / CONFLICTING / FALSE durumlarını kullan. Kaynak yoksa kesin doğru deme.',
  'quality-controller':
    'Dil, yapı, eksik bağlam ve clickbait kontrolü yap. Overall quality skorunu açıklanabilir tut.',
  'legal-risk':
    'Hakaret, iftira, KVKK, çocuk kimliği, masumiyet karinesi, telif, nefret söylemi tara. HIGH/CRITICAL → human approval.',
  'seo-editor':
    'Başlık 55–65, meta 145–160 karakter hedefle. Anahtar kelimeyi doğal kullan; yanıltıcı SERP başlığı yazma.',
  'visual-editor':
    'Görsel-haber uyumunu kontrol et. Alt metin üret. Telif şüpheli görselleri işaretle.',
  'social-director': SOCIAL_DIRECTOR_INSTRUCTIONS,
  'city-smm': CITY_SMM_ROLE_INSTRUCTIONS,
  'algorithm-analyst':
    'Yalnızca öneri üret. Production ağırlıklarını doğrudan değiştirme. Simülasyon + human approval zorunlu.',
  'learning-analyst':
    'İnsan düzeltmelerinden pattern çıkar, rule proposal yaz. Production kuralını kendi başına değiştirme.',
  publisher: 'Dağıtım ve yayın kapılarında risk seviyesine göre human-in-the-loop uygula.',
  reporter: 'Kaynaklara sadık kal, araştırma notlarını kanıtla destekle, uydurma detay ekleme.',
  writer: 'Türkçe editoryal üslup kullan; kaynak özeti ile uyumlu yaz; abartılı sıfatlardan kaçın.',
}

export function specToAgent(spec: OrgSeedSpec, now = Date.now()): NewsroomAgent {
  return {
    id: spec.id,
    name: spec.name,
    displayName: spec.displayName,
    description: spec.description,
    roleTemplateId: spec.roleTemplateId,
    departmentId: spec.departmentId,
    managerAgentId: spec.managerAgentId,
    managerHumanId: null,
    subordinateAgentIds: [],
    status: 'active',
    autonomyLevel: spec.autonomyLevel,
    permissions: spec.permissions,
    allowedAgentIds: [],
    territories: spec.territories,
    categories: spec.categories,
    languages: ['tr'],
    modelConfig: {
      primaryProvider: 'deepseek',
      primaryModel: process.env.DEEPSEEK_NEWS_MODEL?.trim() || 'deepseek-v4-flash',
      fallbackProvider: 'gemini',
      fallbackModel: 'gemini-2.0-flash',
      temperature: 0.4,
      maxTokens: 4096,
      memoryEnabled: true,
      factCheckRequired: spec.roleTemplateId === 'fact-checker' || spec.roleTemplateId === 'desk-editor',
      humanApprovalThreshold: spec.autonomyLevel <= 1 ? 0.7 : 0.9,
      retryCount: 2,
      timeoutMs: 60_000,
    },
    tools: spec.tools,
    customInstructions: ROLE_DEFAULT_INSTRUCTIONS[spec.roleTemplateId],
    legacyAiEditorId: null,
    createdAt: now,
    updatedAt: now,
  }
}
