/**
 * Core newsroom org seed — leadership + desks + writing/digital.
 * City local editors / 81 SMM are linked or bulk-seeded separately.
 */
import type {
  AgentDepartmentId,
  AgentRoleTemplateId,
  AutonomyLevel,
  NewsroomAgent,
} from '@/types/newsroomOs'
import type { CmsPermission } from '@/types/cms'

export interface OrgSeedSpec {
  id: string
  name: string
  displayName: string
  description: string
  roleTemplateId: AgentRoleTemplateId
  departmentId: AgentDepartmentId
  managerAgentId: string | null
  autonomyLevel: AutonomyLevel
  categories: string[]
  territories: string[]
  permissions: CmsPermission[]
  tools: string[]
}

const BASE_PERMS: CmsPermission[] = ['ai:use', 'news:read']

export const ORG_SEED_SPECS: OrgSeedSpec[] = [
  {
    id: 'agent-eic',
    name: 'genel-yayin-yonetmeni',
    displayName: 'Genel Yayın Yönetmeni AI',
    description: 'Tüm AI newsroom operasyonunun en üst yöneticisi',
    roleTemplateId: 'editor-in-chief',
    departmentId: 'executive',
    managerAgentId: null,
    autonomyLevel: 2,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'agents:manage', 'news:publish', 'ai:configure'],
    tools: ['delegate', 'approve', 'escalate'],
  },
  {
    id: 'agent-deputy',
    name: 'genel-yayin-yardimcisi',
    displayName: 'Genel Yayın Yönetmen Yardımcısı AI',
    description: 'EIC yardımcısı — koordinasyon ve escalation',
    roleTemplateId: 'deputy-editor',
    departmentId: 'executive',
    managerAgentId: 'agent-eic',
    autonomyLevel: 2,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'agents:delegate', 'news:publish'],
    tools: ['delegate', 'approve'],
  },
  {
    id: 'agent-news-director',
    name: 'haber-muduru',
    displayName: 'Haber Müdürü AI',
    description: 'Masalar ve yazı işleri koordinasyonu',
    roleTemplateId: 'news-director',
    departmentId: 'newsroom',
    managerAgentId: 'agent-eic',
    autonomyLevel: 2,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'news:edit', 'news:publish', 'agents:delegate'],
    tools: ['assign-desk', 'priority'],
  },
  {
    id: 'agent-desk-gundem',
    name: 'gundem-muduru',
    displayName: 'Gündem Müdürü AI',
    description: 'Ulusal gündem masası',
    roleTemplateId: 'desk-editor',
    departmentId: 'desk-gundem',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 2,
    categories: ['gundem', 'siyaset', 'son-dakika'],
    territories: [],
    permissions: [...BASE_PERMS, 'news:edit', 'news:create'],
    tools: ['write', 'research'],
  },
  {
    id: 'agent-desk-economy',
    name: 'ekonomi-muduru',
    displayName: 'Ekonomi Müdürü AI',
    description: 'Ekonomi / finans masası',
    roleTemplateId: 'desk-editor',
    departmentId: 'desk-economy',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 2,
    categories: ['ekonomi', 'finans', 'borsa'],
    territories: [],
    permissions: [...BASE_PERMS, 'news:edit', 'news:create'],
    tools: ['write', 'research'],
  },
  {
    id: 'agent-desk-sports',
    name: 'spor-muduru',
    displayName: 'Spor Müdürü AI',
    description: 'Spor masası',
    roleTemplateId: 'desk-editor',
    departmentId: 'desk-sports',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 2,
    categories: ['spor', 'futbol', 'basketbol'],
    territories: [],
    permissions: [...BASE_PERMS, 'news:edit', 'news:create'],
    tools: ['write', 'research'],
  },
  {
    id: 'agent-desk-local',
    name: 'yerel-yayin-muduru',
    displayName: 'Yerel Yayın Müdürü AI',
    description: '81 il yerel editör ağı yöneticisi',
    roleTemplateId: 'desk-editor',
    departmentId: 'desk-local',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 2,
    categories: ['yerel-haber', 'yerel-duyuru'],
    territories: [],
    permissions: [...BASE_PERMS, 'news:edit', 'locations:manage', 'agents:delegate'],
    tools: ['assign-city', 'write'],
  },
  {
    id: 'agent-fact-check',
    name: 'fact-check',
    displayName: 'Fact Check AI',
    description: 'İddia çıkarımı ve doğrulama',
    roleTemplateId: 'fact-checker',
    departmentId: 'writing',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 1,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS],
    tools: ['fact-check', 'evidence'],
  },
  {
    id: 'agent-quality',
    name: 'quality-control',
    displayName: 'Quality Controller AI',
    description: 'Editoryal kalite kontrol',
    roleTemplateId: 'quality-controller',
    departmentId: 'writing',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 1,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS],
    tools: ['quality-score'],
  },
  {
    id: 'agent-legal',
    name: 'legal-risk',
    displayName: 'Legal / Risk AI',
    description: 'Hakaret, KVKK, masumiyet, telif risk taraması',
    roleTemplateId: 'legal-risk',
    departmentId: 'writing',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 1,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS],
    tools: ['risk-scan'],
  },
  {
    id: 'agent-seo',
    name: 'seo-editor',
    displayName: 'SEO Editor AI',
    description: 'Başlık, meta, discover uyumu',
    roleTemplateId: 'seo-editor',
    departmentId: 'writing',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 2,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'seo:edit'],
    tools: ['seo-optimize'],
  },
  {
    id: 'agent-visual',
    name: 'visual-editor',
    displayName: 'Visual Editor AI',
    description: 'Görsel seçim ve alt metin',
    roleTemplateId: 'visual-editor',
    departmentId: 'writing',
    managerAgentId: 'agent-news-director',
    autonomyLevel: 2,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS],
    tools: ['image-select'],
  },
  {
    id: 'agent-digital-director',
    name: 'dijital-yayin-muduru',
    displayName: 'Dijital Yayın Müdürü AI',
    description: 'Discover, push, video, sosyal üst yönetim',
    roleTemplateId: 'publisher',
    departmentId: 'digital',
    managerAgentId: 'agent-eic',
    autonomyLevel: 2,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'social:manage', 'agents:delegate'],
    tools: ['distribute', 'push'],
  },
  {
    id: 'agent-social-director',
    name: 'social-media-director',
    displayName: 'Social Media Director AI',
    description: '81 İl SMM ağının yöneticisi',
    roleTemplateId: 'social-director',
    departmentId: 'social',
    managerAgentId: 'agent-digital-director',
    autonomyLevel: 2,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'social:manage', 'social:publish', 'agents:delegate'],
    tools: ['smm-assign', 'campaign', 'escalate'],
  },
  {
    id: 'agent-algorithm',
    name: 'algorithm-analyst',
    displayName: 'Algorithm Agent',
    description: 'Feed ağırlık önerileri — production değişikliği yapmaz',
    roleTemplateId: 'algorithm-analyst',
    departmentId: 'algorithm',
    managerAgentId: 'agent-digital-director',
    autonomyLevel: 0,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'algorithm:view'],
    tools: ['analyze-feed', 'propose-weights'],
  },
  {
    id: 'agent-learning',
    name: 'learning-analyst',
    displayName: 'Learning Agent',
    description: 'Diff analizi → rule proposal (human approve zorunlu)',
    roleTemplateId: 'learning-analyst',
    departmentId: 'learning',
    managerAgentId: 'agent-eic',
    autonomyLevel: 0,
    categories: [],
    territories: [],
    permissions: [...BASE_PERMS, 'ai:configure'],
    tools: ['diff-analyze', 'propose-rule'],
  },
]

export const ROLE_TEMPLATE_LABELS: Record<AgentRoleTemplateId, string> = {
  'editor-in-chief': 'Genel Yayın Yönetmeni',
  'deputy-editor': 'Yardımcı',
  'news-director': 'Haber Müdürü',
  'desk-editor': 'Masa Editörü',
  'local-editor': 'Yerel Editör',
  reporter: 'Muhabir',
  writer: 'Yazar',
  'fact-checker': 'Fact Checker',
  'quality-controller': 'Quality',
  'legal-risk': 'Legal/Risk',
  'seo-editor': 'SEO',
  'visual-editor': 'Visual',
  'social-director': 'Social Director',
  'city-smm': 'İl SMM',
  'algorithm-analyst': 'Algorithm',
  'learning-analyst': 'Learning',
  publisher: 'Yayın',
}

export const DEPARTMENT_LABELS: Record<AgentDepartmentId, string> = {
  executive: 'Üst Yönetim',
  newsroom: 'Haber Merkezi',
  'desk-gundem': 'Gündem Masası',
  'desk-local': 'Yerel Masa',
  'desk-sports': 'Spor Masası',
  'desk-economy': 'Ekonomi Masası',
  writing: 'Yazı İşleri',
  digital: 'Dijital Yayın',
  social: 'Sosyal Medya',
  algorithm: 'Algoritma',
  learning: 'Öğrenme',
}

export function specToAgent(spec: OrgSeedSpec, now = Date.now()): NewsroomAgent {
  return {
    id: spec.id,
    name: spec.name,
    displayName: spec.displayName,
    description: spec.description,
    roleTemplateId: spec.roleTemplateId,
    departmentId: spec.departmentId,
    managerAgentId: spec.managerAgentId,
    managerHumanId: null,
    subordinateAgentIds: [],
    status: 'active',
    autonomyLevel: spec.autonomyLevel,
    permissions: spec.permissions,
    allowedAgentIds: [],
    territories: spec.territories,
    categories: spec.categories,
    languages: ['tr'],
    modelConfig: {
      primaryProvider: 'deepseek',
      primaryModel: process.env.DEEPSEEK_NEWS_MODEL?.trim() || 'deepseek-v4-flash',
      fallbackProvider: 'gemini',
      fallbackModel: 'gemini-2.0-flash',
      temperature: 0.4,
      maxTokens: 4096,
      memoryEnabled: true,
      factCheckRequired: spec.roleTemplateId === 'fact-checker' || spec.roleTemplateId === 'desk-editor',
      humanApprovalThreshold: spec.autonomyLevel <= 1 ? 0.7 : 0.9,
      retryCount: 2,
      timeoutMs: 60_000,
    },
    tools: spec.tools,
    legacyAiEditorId: null,
    createdAt: now,
    updatedAt: now,
  }
}
