-- LP6 Publisher Themes — accent color field
--
-- Hand-authored, NOT generated by `drizzle-kit generate`. See the note
-- delivered alongside this file for why: this repo's migration snapshot
-- chain (src/db/migrations/meta/*_snapshot.json) is missing snapshots for
-- migrations 0002 through 0035, so `drizzle-kit generate` cannot compute a
-- correct incremental diff right now -- it tried to re-CREATE every table
-- in the schema. That is a pre-existing repo issue, unrelated to this
-- change, and this file deliberately works around it rather than papering
-- over it.
--
-- This statement is the ONLY schema change introduced by the LP6
-- accentColorHex feature: one new, nullable, additive column on the
-- existing `publishers` table. It does not touch any other table, does
-- not drop or rename anything, and is safe to run against the live
-- database without a backfill (existing rows simply get NULL, which the
-- application already treats as "no accent -- NaHaber's neutral default").

ALTER TABLE "publishers" ADD COLUMN IF NOT EXISTS "accent_color_hex" varchar(7);
