/**
 * Scraper Source Definitions — RSS'i olmayan veya 403 veren yerel haber siteleri.
 *
 * Her kaynak için:
 *   listUrls    — Haberlerin listelendiği sayfalar (anasayfa veya kategori sayfası)
 *   linkSelector — Haber linklerini seçen CSS selector (opsiyonel, generic fallback var)
 *   linkPattern  — URL'de bulunması gereken desen (regex string)
 *   maxItems     — Her run'da işlenecek max haber sayısı
 *   localMeta    — Şehir/ilçe bilgisi
 */

export interface ScraperSource {
  id: string
  label: string
  enabled: boolean
  listUrls: string[]
  /** CSS selector for <a> tags on the list page. Defaults to generic article link detection. */
  linkSelector?: string
  /** Regex pattern — URL must match to be included. */
  linkPattern?: string
  /** Regex pattern — URL must NOT match to be excluded. */
  linkExcludePattern?: string
  maxItems: number
  localMeta: {
    citySlug: string
    cityName: string
    district?: string
  }
}

/**
 * Scraper sources — sorted by city slug alphabetically.
 * Add new portals here when RSS is blocked or unavailable.
 */
export const SCRAPER_PORTAL_FEEDS: ScraperSource[] = [
  // ── Çanakkale ────────────────────────────────────────────────────────────
  {
    id: 'scraper-canakkale-kaleninsesi',
    label: 'Kalenin Sesi (scraper)',
    enabled: false, // 2026-08-02 audit: HTTP 403
    listUrls: ['https://www.kaleninsesi.com/', 'https://www.kaleninsesi.com/son-dakika'],
    linkPattern: '/\\d{5,}',
    maxItems: 5,
    localMeta: { citySlug: 'canakkale', cityName: 'Çanakkale' },
  },
  {
    id: 'scraper-canakkale-gundem',
    label: 'Çanakkale Gündem (scraper)',
    enabled: true,
    listUrls: ['https://canakkalegundem.net/', 'https://canakkalegundem.net/son-dakika'],
    linkPattern: '/haber/|/\\d{5,}',
    maxItems: 5,
    localMeta: { citySlug: 'canakkale', cityName: 'Çanakkale' },
  },
  {
    id: 'scraper-canakkale-can-insesi',
    label: 'Çan İnsesi (scraper)',
    enabled: true,
    listUrls: ['https://www.caninsesi.com.tr/'],
    linkPattern: '/haber/|/detay/|/\\d{5,}',
    maxItems: 5,
    localMeta: { citySlug: 'canakkale', cityName: 'Çanakkale', district: 'Çan' },
  },
  {
    id: 'scraper-canakkale-tontv',
    label: 'Ton TV (scraper)',
    enabled: true,
    listUrls: ['https://www.tontv.com.tr/canakkale-haber', 'https://www.tontv.com.tr/'],
    linkPattern: '/haber/\\d+/',
    maxItems: 5,
    localMeta: { citySlug: 'canakkale', cityName: 'Çanakkale' },
  },

  // ── Bursa ─────────────────────────────────────────────────────────────────
  {
    id: 'scraper-bursa-olay',
    label: 'Bursa Olay (scraper)',
    enabled: false, // 2026-08-02 audit: no usable page body
    listUrls: ['https://www.bursaolay.com/', 'https://www.bursaolay.com/son-dakika'],
    linkPattern: '/haber/|/\\d{5,}',
    maxItems: 5,
    localMeta: { citySlug: 'bursa', cityName: 'Bursa' },
  },

  // ── İzmir ─────────────────────────────────────────────────────────────────
  {
    id: 'scraper-izmir-yasamgazetesi',
    label: 'İzmir Yaşam Gazetesi (scraper)',
    enabled: true,
    listUrls: ['https://www.izmirgazetesi.com.tr/'],
    linkPattern: '/haber/|/detay/|/\\d{4,}',
    maxItems: 5,
    localMeta: { citySlug: 'izmir', cityName: 'İzmir' },
  },

  // ── Ankara ────────────────────────────────────────────────────────────────
  {
    id: 'scraper-ankara-yerel',
    label: 'Ankara Yerel Haber (scraper)',
    enabled: false, // 2026-08-02 audit: fetch failed
    listUrls: ['https://www.ankarayerelhaber.com/'],
    linkPattern: '/haber/|/\\d{5,}',
    maxItems: 5,
    localMeta: { citySlug: 'ankara', cityName: 'Ankara' },
  },

  // ── İstanbul ─────────────────────────────────────────────────────────────
  {
    id: 'scraper-istanbul-gazete',
    label: 'İstanbul Gazete (scraper)',
    enabled: true,
    listUrls: ['https://www.istanbulgazetesi.com.tr/'],
    linkPattern: '/haber/|/\\d{5,}',
    maxItems: 5,
    localMeta: { citySlug: 'istanbul', cityName: 'İstanbul' },
  },

  // ── Antalya ───────────────────────────────────────────────────────────────
  {
    id: 'scraper-antalya-olay',
    label: 'Antalya Olay (scraper)',
    enabled: false, // 2026-08-02 audit: fetch failed
    listUrls: ['https://www.antalyaolay.com/'],
    linkPattern: '/haber/|/\\d{5,}',
    maxItems: 5,
    localMeta: { citySlug: 'antalya', cityName: 'Antalya' },
  },

  // ── Konya ─────────────────────────────────────────────────────────────────
  {
    id: 'scraper-konya-ovahaber',
    label: 'Konya Ova Haber (scraper)',
    enabled: false, // 2026-08-02 audit: fetch failed
    listUrls: ['https://www.konyaovahaber.com/'],
    linkPattern: '/haber/|/\\d{5,}',
    maxItems: 5,
    localMeta: { citySlug: 'konya', cityName: 'Konya' },
  },

  // ── Kayseri ───────────────────────────────────────────────────────────────
  {
    id: 'scraper-kayseri-ses',
    label: 'Kayseri Ses (scraper)',
    enabled: true,
    listUrls: ['https://www.kayseri.com.tr/'],
    linkPattern: '/haber/|/\\d{5,}',
    maxItems: 5,
    localMeta: { citySlug: 'kayseri', cityName: 'Kayseri' },
  },

  // ── Trabzon ───────────────────────────────────────────────────────────────
  {
    id: 'scraper-trabzon-haber',
    label: 'Trabzon Haber (scraper)',
    enabled: true,
    listUrls: ['https://www.trabzonhaber.com/'],
    linkPattern: '/haber/|/\\d{5,}',
    maxItems: 5,
    localMeta: { citySlug: 'trabzon', cityName: 'Trabzon' },
  },

  // ── Samsun ────────────────────────────────────────────────────────────────
  {
    id: 'scraper-samsun-yerel',
    label: 'Samsun Yerel Haber (scraper)',
    enabled: true,
    listUrls: ['https://www.samsunhaber.com/'],
    linkPattern: '/haber/|/\\d{5,}',
    maxItems: 5,
    localMeta: { citySlug: 'samsun', cityName: 'Samsun' },
  },

  // ── Gaziantep ─────────────────────────────────────────────────────────────
  {
    id: 'scraper-gaziantep-olay',
    label: 'Gaziantep Olay (scraper)',
    enabled: false, // 2026-08-02 audit: fetch failed
    listUrls: ['https://www.gaziantepolay.com/'],
    linkPattern: '/haber/|/\\d{5,}',
    maxItems: 5,
    localMeta: { citySlug: 'gaziantep', cityName: 'Gaziantep' },
  },

  // ── Diyarbakır ────────────────────────────────────────────────────────────
  {
    id: 'scraper-diyarbakir-haber',
    label: 'Diyarbakır Haber (scraper)',
    enabled: true,
    listUrls: ['https://www.diyarbakirhaber.com.tr/'],
    linkPattern: '/haber/|/\\d{5,}',
    maxItems: 5,
    localMeta: { citySlug: 'diyarbakir', cityName: 'Diyarbakır' },
  },

  // ── Erzurum ───────────────────────────────────────────────────────────────
  {
    id: 'scraper-erzurum-haber',
    label: 'Erzurum Haber (scraper)',
    enabled: true,
    listUrls: ['https://www.erzurumhaber.com.tr/'],
    linkPattern: '/haber/|/\\d{5,}',
    maxItems: 5,
    localMeta: { citySlug: 'erzurum', cityName: 'Erzurum' },
  },

  // ── Çanakkale — ek kaynaklar ──────────────────────────────────────────────
  {
    id: 'scraper-canakkale-tekinugurlu',
    label: 'Tekin Uğurlu (scraper)',
    enabled: true,
    listUrls: ['https://tekinugurlu.com/'],
    linkPattern: '/\\d{4,}|/haber/',
    maxItems: 5,
    localMeta: { citySlug: 'canakkale', cityName: 'Çanakkale' },
  },

  // ── DHA Şehir Sayfaları (81 il) ───────────────────────────────────────────
  // Kaynak: http://www.dha.com.tr/{il-slug}-haber/
  // Makale URL pattern: /{kategori}/{slug}-{7-haneli-id}
  {
    id: 'dha-city-adana',
    label: 'DHA Adana (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/adana-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'adana', cityName: 'Adana' },
  },
  {
    id: 'dha-city-adiyaman',
    label: 'DHA Adıyaman (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/adiyaman-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'adiyaman', cityName: 'Adıyaman' },
  },
  {
    id: 'dha-city-afyonkarahisar',
    label: 'DHA Afyonkarahisar (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/afyonkarahisar-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'afyonkarahisar', cityName: 'Afyonkarahisar' },
  },
  {
    id: 'dha-city-agri',
    label: 'DHA Ağrı (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/agri-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'agri', cityName: 'Ağrı' },
  },
  {
    id: 'dha-city-aksaray',
    label: 'DHA Aksaray (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/aksaray-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'aksaray', cityName: 'Aksaray' },
  },
  {
    id: 'dha-city-amasya',
    label: 'DHA Amasya (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/amasya-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'amasya', cityName: 'Amasya' },
  },
  {
    id: 'dha-city-ankara',
    label: 'DHA Ankara (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/ankara-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'ankara', cityName: 'Ankara' },
  },
  {
    id: 'dha-city-antalya',
    label: 'DHA Antalya (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/antalya-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'antalya', cityName: 'Antalya' },
  },
  {
    id: 'dha-city-ardahan',
    label: 'DHA Ardahan (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/ardahan-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'ardahan', cityName: 'Ardahan' },
  },
  {
    id: 'dha-city-artvin',
    label: 'DHA Artvin (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/artvin-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'artvin', cityName: 'Artvin' },
  },
  {
    id: 'dha-city-aydin',
    label: 'DHA Aydın (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/aydin-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'aydin', cityName: 'Aydın' },
  },
  {
    id: 'dha-city-balikesir',
    label: 'DHA Balıkesir (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/balikesir-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'balikesir', cityName: 'Balıkesir' },
  },
  {
    id: 'dha-city-bartin',
    label: 'DHA Bartın (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/bartin-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'bartin', cityName: 'Bartın' },
  },
  {
    id: 'dha-city-batman',
    label: 'DHA Batman (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/batman-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'batman', cityName: 'Batman' },
  },
  {
    id: 'dha-city-bayburt',
    label: 'DHA Bayburt (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/bayburt-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'bayburt', cityName: 'Bayburt' },
  },
  {
    id: 'dha-city-bilecik',
    label: 'DHA Bilecik (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/bilecik-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'bilecik', cityName: 'Bilecik' },
  },
  {
    id: 'dha-city-bingol',
    label: 'DHA Bingöl (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/bingol-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'bingol', cityName: 'Bingöl' },
  },
  {
    id: 'dha-city-bitlis',
    label: 'DHA Bitlis (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/bitlis-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'bitlis', cityName: 'Bitlis' },
  },
  {
    id: 'dha-city-bolu',
    label: 'DHA Bolu (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/bolu-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'bolu', cityName: 'Bolu' },
  },
  {
    id: 'dha-city-burdur',
    label: 'DHA Burdur (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/burdur-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'burdur', cityName: 'Burdur' },
  },
  {
    id: 'dha-city-bursa',
    label: 'DHA Bursa (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/bursa-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'bursa', cityName: 'Bursa' },
  },
  {
    id: 'dha-city-canakkale',
    label: 'DHA Çanakkale (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/canakkale-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'canakkale', cityName: 'Çanakkale' },
  },
  {
    id: 'dha-city-cankiri',
    label: 'DHA Çankırı (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/cankiri-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'cankiri', cityName: 'Çankırı' },
  },
  {
    id: 'dha-city-corum',
    label: 'DHA Çorum (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/corum-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'corum', cityName: 'Çorum' },
  },
  {
    id: 'dha-city-denizli',
    label: 'DHA Denizli (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/denizli-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'denizli', cityName: 'Denizli' },
  },
  {
    id: 'dha-city-diyarbakir',
    label: 'DHA Diyarbakır (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/diyarbakir-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'diyarbakir', cityName: 'Diyarbakır' },
  },
  {
    id: 'dha-city-duzce',
    label: 'DHA Düzce (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/duzce-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'duzce', cityName: 'Düzce' },
  },
  {
    id: 'dha-city-edirne',
    label: 'DHA Edirne (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/edirne-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'edirne', cityName: 'Edirne' },
  },
  {
    id: 'dha-city-elazig',
    label: 'DHA Elazığ (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/elazig-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'elazig', cityName: 'Elazığ' },
  },
  {
    id: 'dha-city-erzincan',
    label: 'DHA Erzincan (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/erzincan-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'erzincan', cityName: 'Erzincan' },
  },
  {
    id: 'dha-city-erzurum',
    label: 'DHA Erzurum (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/erzurum-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'erzurum', cityName: 'Erzurum' },
  },
  {
    id: 'dha-city-eskisehir',
    label: 'DHA Eskişehir (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/eskisehir-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'eskisehir', cityName: 'Eskişehir' },
  },
  {
    id: 'dha-city-gaziantep',
    label: 'DHA Gaziantep (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/gaziantep-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'gaziantep', cityName: 'Gaziantep' },
  },
  {
    id: 'dha-city-giresun',
    label: 'DHA Giresun (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/giresun-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'giresun', cityName: 'Giresun' },
  },
  {
    id: 'dha-city-gumushane',
    label: 'DHA Gümüşhane (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/gumushane-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'gumushane', cityName: 'Gümüşhane' },
  },
  {
    id: 'dha-city-hakkari',
    label: 'DHA Hakkari (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/hakkari-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'hakkari', cityName: 'Hakkari' },
  },
  {
    id: 'dha-city-hatay',
    label: 'DHA Hatay (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/hatay-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'hatay', cityName: 'Hatay' },
  },
  {
    id: 'dha-city-igdir',
    label: 'DHA Iğdır (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/igdir-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'igdir', cityName: 'Iğdır' },
  },
  {
    id: 'dha-city-isparta',
    label: 'DHA Isparta (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/isparta-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'isparta', cityName: 'Isparta' },
  },
  {
    id: 'dha-city-istanbul',
    label: 'DHA İstanbul (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/istanbul-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'istanbul', cityName: 'İstanbul' },
  },
  {
    id: 'dha-city-izmir',
    label: 'DHA İzmir (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/izmir-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'izmir', cityName: 'İzmir' },
  },
  {
    id: 'dha-city-kahramanmaras',
    label: 'DHA Kahramanmaraş (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/kahramanmaras-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'kahramanmaras', cityName: 'Kahramanmaraş' },
  },
  {
    id: 'dha-city-karabuk',
    label: 'DHA Karabük (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/karabuk-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'karabuk', cityName: 'Karabük' },
  },
  {
    id: 'dha-city-karaman',
    label: 'DHA Karaman (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/karaman-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'karaman', cityName: 'Karaman' },
  },
  {
    id: 'dha-city-kars',
    label: 'DHA Kars (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/kars-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'kars', cityName: 'Kars' },
  },
  {
    id: 'dha-city-kastamonu',
    label: 'DHA Kastamonu (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/kastamonu-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'kastamonu', cityName: 'Kastamonu' },
  },
  {
    id: 'dha-city-kayseri',
    label: 'DHA Kayseri (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/kayseri-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'kayseri', cityName: 'Kayseri' },
  },
  {
    id: 'dha-city-kirikkale',
    label: 'DHA Kırıkkale (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/kirikkale-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'kirikkale', cityName: 'Kırıkkale' },
  },
  {
    id: 'dha-city-kirklareli',
    label: 'DHA Kırklareli (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/kirklareli-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'kirklareli', cityName: 'Kırklareli' },
  },
  {
    id: 'dha-city-kirsehir',
    label: 'DHA Kırşehir (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/kirsehir-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'kirsehir', cityName: 'Kırşehir' },
  },
  {
    id: 'dha-city-kilis',
    label: 'DHA Kilis (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/kilis-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'kilis', cityName: 'Kilis' },
  },
  {
    id: 'dha-city-kocaeli',
    label: 'DHA Kocaeli (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/kocaeli-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'kocaeli', cityName: 'Kocaeli' },
  },
  {
    id: 'dha-city-konya',
    label: 'DHA Konya (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/konya-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'konya', cityName: 'Konya' },
  },
  {
    id: 'dha-city-kutahya',
    label: 'DHA Kütahya (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/kutahya-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'kutahya', cityName: 'Kütahya' },
  },
  {
    id: 'dha-city-malatya',
    label: 'DHA Malatya (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/malatya-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'malatya', cityName: 'Malatya' },
  },
  {
    id: 'dha-city-manisa',
    label: 'DHA Manisa (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/manisa-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'manisa', cityName: 'Manisa' },
  },
  {
    id: 'dha-city-mardin',
    label: 'DHA Mardin (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/mardin-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'mardin', cityName: 'Mardin' },
  },
  {
    id: 'dha-city-mersin',
    label: 'DHA Mersin (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/mersin-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'mersin', cityName: 'Mersin' },
  },
  {
    id: 'dha-city-mugla',
    label: 'DHA Muğla (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/mugla-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'mugla', cityName: 'Muğla' },
  },
  {
    id: 'dha-city-mus',
    label: 'DHA Muş (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/mus-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'mus', cityName: 'Muş' },
  },
  {
    id: 'dha-city-nevsehir',
    label: 'DHA Nevşehir (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/nevsehir-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'nevsehir', cityName: 'Nevşehir' },
  },
  {
    id: 'dha-city-nigde',
    label: 'DHA Niğde (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/nigde-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'nigde', cityName: 'Niğde' },
  },
  {
    id: 'dha-city-ordu',
    label: 'DHA Ordu (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/ordu-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'ordu', cityName: 'Ordu' },
  },
  {
    id: 'dha-city-osmaniye',
    label: 'DHA Osmaniye (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/osmaniye-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'osmaniye', cityName: 'Osmaniye' },
  },
  {
    id: 'dha-city-rize',
    label: 'DHA Rize (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/rize-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'rize', cityName: 'Rize' },
  },
  {
    id: 'dha-city-sakarya',
    label: 'DHA Sakarya (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/sakarya-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'sakarya', cityName: 'Sakarya' },
  },
  {
    id: 'dha-city-samsun',
    label: 'DHA Samsun (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/samsun-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'samsun', cityName: 'Samsun' },
  },
  {
    id: 'dha-city-siirt',
    label: 'DHA Siirt (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/siirt-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'siirt', cityName: 'Siirt' },
  },
  {
    id: 'dha-city-sinop',
    label: 'DHA Sinop (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/sinop-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'sinop', cityName: 'Sinop' },
  },
  {
    id: 'dha-city-sivas',
    label: 'DHA Sivas (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/sivas-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'sivas', cityName: 'Sivas' },
  },
  {
    id: 'dha-city-sanliurfa',
    label: 'DHA Şanlıurfa (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/sanliurfa-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'sanliurfa', cityName: 'Şanlıurfa' },
  },
  {
    id: 'dha-city-sirnak',
    label: 'DHA Şırnak (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/sirnak-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'sirnak', cityName: 'Şırnak' },
  },
  {
    id: 'dha-city-tekirdag',
    label: 'DHA Tekirdağ (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/tekirdag-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'tekirdag', cityName: 'Tekirdağ' },
  },
  {
    id: 'dha-city-tokat',
    label: 'DHA Tokat (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/tokat-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'tokat', cityName: 'Tokat' },
  },
  {
    id: 'dha-city-trabzon',
    label: 'DHA Trabzon (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/trabzon-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'trabzon', cityName: 'Trabzon' },
  },
  {
    id: 'dha-city-tunceli',
    label: 'DHA Tunceli (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/tunceli-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'tunceli', cityName: 'Tunceli' },
  },
  {
    id: 'dha-city-usak',
    label: 'DHA Uşak (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/usak-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'usak', cityName: 'Uşak' },
  },
  {
    id: 'dha-city-van',
    label: 'DHA Van (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/van-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'van', cityName: 'Van' },
  },
  {
    id: 'dha-city-yalova',
    label: 'DHA Yalova (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/yalova-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'yalova', cityName: 'Yalova' },
  },
  {
    id: 'dha-city-yozgat',
    label: 'DHA Yozgat (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/yozgat-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'yozgat', cityName: 'Yozgat' },
  },
  {
    id: 'dha-city-zonguldak',
    label: 'DHA Zonguldak (scraper)',
    enabled: true,
    listUrls: ['http://www.dha.com.tr/zonguldak-haber/'],
    linkPattern: '/-\\d{7}',
    maxItems: 3,
    localMeta: { citySlug: 'zonguldak', cityName: 'Zonguldak' },
  },
]

/** Enabled scraper sources only */
export function getEnabledScraperSources(): ScraperSource[] {
  return SCRAPER_PORTAL_FEEDS.filter(s => s.enabled)
}

/** Scraper sources for a specific city */
export function getScraperSourcesForCity(citySlug: string): ScraperSource[] {
  return SCRAPER_PORTAL_FEEDS.filter(
    s => s.enabled && s.localMeta.citySlug === citySlug
  )
}
