/** Turkish geographic region (coğrafi bölge) per province slug. */
export const PROVINCE_REGION_BY_SLUG: Readonly<Record<string, string>> = {
  adana: 'Akdeniz',
  adiyaman: 'Güneydoğu Anadolu',
  afyonkarahisar: 'Ege',
  agri: 'Doğu Anadolu',
  aksaray: 'İç Anadolu',
  amasya: 'Karadeniz',
  ankara: 'İç Anadolu',
  antalya: 'Akdeniz',
  ardahan: 'Doğu Anadolu',
  artvin: 'Karadeniz',
  aydin: 'Ege',
  balikesir: 'Marmara',
  bartin: 'Karadeniz',
  batman: 'Güneydoğu Anadolu',
  bayburt: 'Karadeniz',
  bilecik: 'Marmara',
  bingol: 'Doğu Anadolu',
  bitlis: 'Doğu Anadolu',
  bolu: 'Karadeniz',
  burdur: 'Akdeniz',
  bursa: 'Marmara',
  canakkale: 'Marmara',
  cankiri: 'İç Anadolu',
  corum: 'Karadeniz',
  denizli: 'Ege',
  diyarbakir: 'Güneydoğu Anadolu',
  duzce: 'Karadeniz',
  edirne: 'Marmara',
  elazig: 'Doğu Anadolu',
  erzincan: 'Doğu Anadolu',
  erzurum: 'Doğu Anadolu',
  eskisehir: 'İç Anadolu',
  gaziantep: 'Güneydoğu Anadolu',
  giresun: 'Karadeniz',
  gumushane: 'Karadeniz',
  hakkari: 'Doğu Anadolu',
  hatay: 'Akdeniz',
  igdir: 'Doğu Anadolu',
  isparta: 'Akdeniz',
  istanbul: 'Marmara',
  izmir: 'Ege',
  kahramanmaras: 'Akdeniz',
  karabuk: 'Karadeniz',
  karaman: 'İç Anadolu',
  kars: 'Doğu Anadolu',
  kastamonu: 'Karadeniz',
  kayseri: 'İç Anadolu',
  kilis: 'Güneydoğu Anadolu',
  kirikkale: 'İç Anadolu',
  kirklareli: 'Marmara',
  kirsehir: 'İç Anadolu',
  kocaeli: 'Marmara',
  konya: 'İç Anadolu',
  kutahya: 'Ege',
  malatya: 'Doğu Anadolu',
  manisa: 'Ege',
  mardin: 'Güneydoğu Anadolu',
  mersin: 'Akdeniz',
  mugla: 'Ege',
  mus: 'Doğu Anadolu',
  nevsehir: 'İç Anadolu',
  nigde: 'İç Anadolu',
  ordu: 'Karadeniz',
  osmaniye: 'Akdeniz',
  rize: 'Karadeniz',
  sakarya: 'Marmara',
  samsun: 'Karadeniz',
  sanliurfa: 'Güneydoğu Anadolu',
  siirt: 'Güneydoğu Anadolu',
  sinop: 'Karadeniz',
  sirnak: 'Güneydoğu Anadolu',
  sivas: 'İç Anadolu',
  tekirdag: 'Marmara',
  tokat: 'Karadeniz',
  trabzon: 'Karadeniz',
  tunceli: 'Doğu Anadolu',
  usak: 'Ege',
  van: 'Doğu Anadolu',
  yalova: 'Marmara',
  yozgat: 'İç Anadolu',
  zonguldak: 'Karadeniz',
}
