/**
 * Presentation-only Turkish CMS labels. Do not rename DB enums or API contracts.
 */
export const CMS_STATUS_LABELS: Record<string, string> = {
  draft: 'Taslak',
  DRAFT: 'Taslak',
  active: 'Aktif',
  ACTIVE: 'Aktif',
  archived: 'Arşiv',
  ARCHIVED: 'Arşiv',
  preview: 'Önizleme',
  published: 'Yayında',
  PUBLISHED: 'Yayında',
  APPROVED: 'Onaylandı',
  APPROVED_FOR_AI: 'AI için onaylandı',
  WATCHING: 'İzleniyor',
  ELIGIBLE: 'Uygun',
  REJECTED: 'Reddedildi',
  OPEN: 'Açık',
  HIGH: 'Yüksek',
  HIGH_PRIORITY: 'Yüksek öncelik',
  BREAKING: 'Son Dakika',
  NORMAL: 'Normal',
  LOW: 'Düşük',
  algorithmic: 'Algoritmik',
  ALGORITHMIC: 'Algoritmik',
  manual: 'Manuel',
  MANUAL: 'Manuel',
  category_rail: 'Kategori bandı',
  PROPOSED: 'Önerildi',
  TESTING: 'Testte',
  DEPLOYED: 'Yayınlandı',
  NONE: 'Karar yok',
  BORDERLINE: 'Sınırda',
  CLOSED: 'Kapalı',
  running: 'Çalışıyor',
  success: 'Başarılı',
  failed: 'Başarısız',
  skipped: 'Atlandı',
  pending: 'Bekliyor',
  disabled: 'Devre Dışı',
  idle: 'Boşta',
  schedule: 'Zamanlanmış',
  manual_trigger: 'Manuel',
  PAUSED: 'Duraklatıldı',
  DEGRADED: 'Zayıf',
  DISABLED: 'Kapalı',
  IN_REVIEW: 'İncelemede',
  AI_CANDIDATE: 'AI Adayı',
  NEW: 'Yeni',
  EDITING: 'Düzenleniyor',
  DELETED: 'Silindi',
  SKIPPED: 'Atlandı',
  PRIMARY: 'Birincil',
  SUPPORTING: 'Destekleyici',
  DUPLICATE: 'Mükerrer',
  LOW_QUALITY: 'Düşük kalite',
  MATERIAL_UPDATE: 'Maddi güncelleme',
  TIER_A: 'A Kademe',
  TIER_B: 'B Kademe',
  TIER_C: 'C Kademe',
  RSS: 'RSS',
  SITEMAP: 'Sitemap',
  HTML: 'HTML',
  HTTP: 'HTTP',
  ROLLBACK: 'Geri alındı',
  ROLLBACK_AVAILABLE: 'Geri alınabilir',
  COST_UNKNOWN: 'Maliyet bilinmiyor',
}

export function cmsLabel(value: string | null | undefined, fallback?: string): string {
  if (!value) return fallback || '—'
  return CMS_STATUS_LABELS[value] || CMS_STATUS_LABELS[value.toLowerCase()] || fallback || value
}
